<?php

namespace AppBundle\Repository;

/**
 * UserLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
